backend-final-sdgp/website/models.py
from . import db
from flask_login import UserMixin
from sqlalchemy.sql import func

class Note(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    data = db.Column(db.String(10000))
    # result = db.Column(db.String(10000))
    date = db.Column(db.DateTime(timezone=True), default=func.now())
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'))

class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    email = db.Column(db.String(150), unique=True)
    password = db.Column(db.String(150))
    first_name = db.Column(db.String(150))
    #first_name = db.Column(db.Boolean())
    notes = db.relationship('Note')

backend-final-sdgp/website/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy
from os import path
from flask_login import LoginManager

#db = SQLAlchemy()
#DB_NAME = "database.db"

# def create_app():
#    app = Flask(__name__)
#    app.config['SECRET_KEY'] = 'gjgygjgjyg ouyiutyry'
#    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
#    db.init_app(app)

#    from .views import views
#    from .auth import auth

#    app.register_blueprint(views, url_prefix='/')
#    app.register_blueprint(auth, url_prefix='/')

#    from .models import User, Note

#    create_database(app)
#    return app 

# def create_database(app):
#    if not path.exists('website/' + DB_NAME):
#        db.create_all (app=app)
#        print("Created Database!")

db = SQLAlchemy()
DB_NAME = "database.db"

def create_app():
    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'gjgygjgjyg ouyiutyry'
    app.config['SQLALCHEMY_DATABASE_URI'] = f'sqlite:///{DB_NAME}'
    db.init_app(app)

    

    from .views import views
    from .auth import auth
    from .ml import ml

    app.register_blueprint(views, url_prefix='/')
    app.register_blueprint(auth, url_prefix='/')
    app.register_blueprint(ml, url_prefix='/')

    from .models import User, Note

    with app.app_context():
        db.create_all()
    login_manager = LoginManager()
    login_manager.login_view = 'auth.login'
    login_manager.init_app(app)

    @login_manager.user_loader
    def load_user(id):
        return User.query.get(int(id))    
        
        

    return app

backend-final-sdgp/website/auth.py
from flask import Blueprint, render_template, request, flash, redirect, url_for
from .models import User
from werkzeug.security import generate_password_hash, check_password_hash 
from . import db
from flask_login import login_user, login_required, logout_user, current_user

auth = Blueprint('auth', __name__)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    if request.method == 'POST':
        email = request.form.get('email')
        password = request.form.get('password')

        user = User.query.filter_by(email=email).first()
        if user:
            if check_password_hash(user.password, password):
                flash('Logged in successfully!', category='success')
                login_user(user, remember=True)
                return redirect(url_for('views.dashboard'))
            else: 
                flash('Incorrect password, try again.', category='error')
        else:
            flash('Email does not exist.', category='error')        


    
    return render_template("signin.html" , user=current_user )

@auth.route('/logout')
@login_required
def logout():
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/sign-up', methods=['GET', 'POST'])
def sign_up():
    if request.method == 'POST':
        email = request.form.get('email')
        first_name = request.form.get('firstName')
        password1 = request.form.get('password1')
        password2 = request.form.get('password2')

        user = User.query.filter_by(email=email).first()

        if user:
            flash('Email already exists.', category='error')

        elif len(email) < 4:
            flash('Email must be greater than 3 characters.', category='error')
        elif len(first_name) < 2:
            flash('First name must be greater than 1 characters.', category='error')
            
        elif password1 != password2:
            flash('Passwords do not match.', category='error')
            
        elif len(password1) < 7:
            flash('Password must be at least 6 characters.', category='error')
        else:
            # add user to database
            new_user = User(email=email, first_name=first_name, password=generate_password_hash(password1, method='sha256'))
            db.session.add(new_user)
            db.session.commit()
            login_user(new_user, remember=True)
            flash('Account created!', category='success')
            return redirect(url_for('views.dashboard'))

    return render_template("signup.html", user = current_user)

backend-final-sdgp/website/views.py
import sqlite3
from sqlite3 import Error
from flask import Blueprint, render_template, request, flash , jsonify
from flask_login import login_required, current_user
from .models import Note
from .ml import prediction
from . import db
import json
views = Blueprint('views', __name__)


@views.route('/', methods=['GET', 'POST'])
@login_required
def home():
    return render_template("index.html", user=current_user)
@views.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    return render_template("dashboard.html", user=current_user)

@views.route('/addreview', methods=['GET', 'POST'])
@login_required
def addreview():
    if request.method == 'POST':
        # username = request.form.get('username')
        # title = request.form.get('title')
        # rating = request.form.get('rating')
        note = request.form.get('note')

        if len(note) < 1:
            flash('Note is too short!', category='error')
        else:
            new_note = Note(data=note, user_id=current_user.id)
            db.session.add(new_note)
            db.session.commit()
            flash('Note added!', category='success')
    return render_template("career.html", user=current_user)

@views.route('/viewreview', methods=['GET', 'POST'])
def viewreview():
    return render_template("blog-1.html", user=current_user)

@views.route('/aboutus', methods=['GET', 'POST'])
def aboutus():
    return render_template("about.html", user=current_user)

@views.route('/delete-note', methods=['POST'])
def delete_note():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    if note:
        if note.user_id == current_user.id:
            db.session.delete(note)
            db.session.commit()

    return jsonify({})


@views.route('/input', methods=['GET', 'POST'])
@login_required
def input():
    note = json.loads(request.data)
    noteId = note['noteId']
    note = Note.query.get(noteId)
    print(noteId)
    conn = sqlite3.connect('./instance/database.db')
    cursor = conn.cursor()
    cursor.execute("SELECT data from Note where id=?",(noteId,))
    data = cursor.fetchall()
    print(data)
    # print(type(data))
    input_tuple = data
    output = input_tuple[0][0].strip()
    print(output)
    result = prediction(output)
    print(result)
    return jsonify({
        'result':result
    })
# def input():
#     data = request.json
#     noteId = data['noteId']
#     print(noteId)
#     note = json.loads(request.data)
#     # noteId = note['noteId']
#     note = Note.query.get(noteId)
#     print(note)
#     if note:
#         if note.user_id == current_user.id:
#             result = "Positive"
#             print(result)
#             # return jsonify(result=result)
#             return render_template('career.html', result=result, user=current_user)
#     return jsonify(error='Note not found or user not authorized')
# def input():
#     data = request.json
#     noteId = data['noteId']
#     result = "result"
#     if (request.method == "GET"):
#         with sqlite3.connect("./instance/database.db") as con:

#             cursor = con.cursor()

#             try:
#                 cursor.execute( "SELECT data from Note where id=?",(noteId))
#                     # "SELECT marks.std_id,student.std_fname,student.std_lname,SUM(marks) as total_marks FROM Marks marks JOIN Student student ON marks.std_id = student.std_id WHERE date = CURRENT_DATE GROUP BY marks.std_id;")

#                 rows = cursor.fetchall()
#                 noteList = rows[0]
#                 result = "Positive"
#                 return render_template("career.html", result=result, user=current_user)
#             except Error as e:
#                 print(e)
#         return render_template("career.html", user=current_user)

backend-final-sdgp/website/templates/career.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<title>Vuelo Amigo/AddReview</title>

<link rel="shortcut icon" href="{{ url_for('static', filename='welcome_page/Assets/Img/favicon.png') }}" type="image/x-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">

<!-- Stylesheets -->
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/font-awesome-all.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/flaticon.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/owl.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/jquery.fancybox.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/animate.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/jquery-ui.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/nice-select.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/color/theme-color.css') }}" id="jssDefault" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/switcher-style.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='AddReviewPage/assets/css/responsive.css') }}" rel="stylesheet">

</head>


<!-- page wrapper -->
<body>

    <div class="boxed_wrapper">

        <!--Page Title-->
        <section class="page-title centred" style="background-image: url({{ url_for('static', filename='AddReviewPage/assets/images/background.jpg') }})">
            <div class="auto-container">
                <div class="content-box clearfix">
                    <h1>Add Review</h1>
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{ url_for('views.dashboard') }}">DashBoard</a></li>
                        <li>Add Review</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--End Page Title-->

        <!-- contact-section -->
        <section class="contact-section bg-color-1">
            <div class="auto-container">
                <div class="row align-items-center clearfix">
                    <div class="col-lg-6 col-md-12 col-sm-12 content-column">
                        <div class="content-box">
                            <div class="sec-title">
                                <h5>Review</h5>
                                <h2>Add Review</h2>
                            </div>
                            <div class="form-inner">
                                <form method="post"> 
                                    <div class="row clearfix">
<!-- {#                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">#}
{#                                            <input type="text" name="username" placeholder="Your User Name" required="">#}
{#                                        </div>#}
{#                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">#}
{#                                            <input type="text" name="title" placeholder="Title " required="">#}
{#                                        </div>#}
{#                                        <div class="col-lg-6 col-md-6 col-sm-12 form-group">#}
{#                                            <select name="rating" id="">#}
{#                                                <option value="Your Rating" selected>Your Rating</option>#}
{#                                                <option value="Very Bad">Very Bad - 01</option>#}
{#                                                <option value="Bad">Bad - 02</option>#}
{#                                                <option value="Avarage">Avarage - 03</option>#}
{#                                                <option value="Good">Good - 04</option>#}
{#                                                <option value="Very Good">Very Good - 05</option>#}
{#                                            </select>#}
{##}
{#                                        </div>#} -->
                                        <div class="col-lg-12 col-md-12 col-sm-12 form-group">
                                            <textarea name="note" id="note" placeholder="Your Review"></textarea>
                                        </div>
                                        <div class="col-lg-12 col-md-12 col-sm-12 form-group message-btn">
                                            <button class="theme-btn btn-one" type="submit" name="submit-form">Add Review</button>
                                            <a href="{{ url_for('views.viewreview') }}" class="theme-btn btn-one">View Reviews</a>
                                        </div>
                                    </div>
                                </form>
                                <ul class="list-group list-group-flush" id="notes">
                                    {% for note in user.notes %}
                                    <li class="list-group-item">
                                        {{ note.data }}
                                        <button type="button" class="close" onClick="deleteNote({{ note.id }})">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <br>
                                        <br>
                                       <!-- <button type="button" class="theme-btn" onClick="inputText({{ note.id }})">
                                           <span aria-hidden="true">Analyze</span>
                                        </button> -->
                                    <br>
                                    <br>
                                        <!-- <p>Result: {{ result }}</p> -->
                                    </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-6 col-md-12 col-sm-12 image-column">
                        <div class="image-box wow fadeInRight animated" data-wow-delay="00ms" data-wow-duration="3000ms">
                            <figure class="image"><img src="{{ url_for('static', filename='AddReviewPage/assets/images/passenger.png') }}" alt=""></figure>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- contact-section end -->

    <!-- jequery plugins -->
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/owl.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/wow.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/validation.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/jquery.fancybox.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/scrollbar.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/isotope.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/jquery.nice-select.min.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/jQuery.style.switcher.min.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/jquery-ui.js') }}"></script>
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/product-filter.js') }}"></script>


    <!-- main-js -->
    <script src="{{ url_for('static', filename='AddReviewPage/assets/js/script.js') }}"></script>
    <script src="{{ url_for('static', filename='/index.js') }}"></script>

        <script type="text/javascript">
            function inputText(noteId){
                fetch("/input", {
                    method: "POST",
                    body: JSON.stringify({ noteId: noteId }),
                }).then((_res) => {
                    window.location.href = "/addreview";
                });
                // data = {
                //     "noteId":noteId
                // }
                // fetch("/input", {
                //   method: "Get",
                //   headers: {
                //     "Content-Type": "application/json",
                //   },
                //   body: JSON.stringify(data),
                // })
                //     .then((response) => response.json())
                //     .then((data) => {
                //         let result = data.result
                //     });
            }
        </script>

        <script type="text/javascript">
			function deleteNote(noteId) {
				fetch("/delete-note", {
					method: "POST",
					body: JSON.stringify({ noteId: noteId }),
				}).then((_res) => {
					window.location.href = "/addreview";
				});
			}
		</script>
</body><!-- End of .page_wrapper -->

</html>

backend-final-sdgp/website/templates/home.html
{% extends "base.html" %} {% block title %} Home {% endblock %} {% block content
%}
<h1 align="center">Notes</h1>
<ul class="list-group list-group-flush" id="notes">
	{% for note in user.notes %}
	<li class="list-group-item">
		{{ note.data }}
		<button type="button" class="close" onClick="deleteNote({{ note.id }})">
			<span aria-hidden="true">&times;</span>
		</button>
	</li>
	{% endfor %}
</ul>

<form method="POST">
	<textarea name="note" id="note" class="form-control"></textarea>
	<br />
	<div align="center">
		<button type="submit" class="btn btn-primary">Add Note</button>
	</div>
</form>
{{user}}{% endblock %}

backend-final-sdgp/website/templates/login.html
{% extends "base.html" %} {% block title %}Login{% endblock %} {% block content
%}
<form method="POST">
	<h3 align="center">Login</h3>
	<div class="form-group">
		<label for="email">Email Address</label>
		<input
			type="email"
			class="form-control"
			id="email"
			name="email"
			placeholder="Enter email"
		/>
	</div>

	<div class="form-group">
		<label for="password">Password</label>
		<input
			type="password"
			class="form-control"
			id="password"
			name="password"
			placeholder="Enter password"
		/>
	</div>
	<br />
	<button type="submit" class="btn btn-primary">Login</button>
</form>
{{user}} {% endblock %}

backend-final-sdgp/website/templates/signin.html
<!DOCTYPE html>
<html lang="en">

<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">

<title></title>

<!-- Fav Icon -->
<link rel="shortcut icon" href="{{ url_for('static', filename='welcome_page/Assets/Img/favicon.png') }}" type="image/x-icon">

<!-- Google Fonts -->
<link href="https://fonts.googleapis.com/css2?family=Rubik:ital,wght@0,300;0,400;0,500;0,600;0,700;0,800;0,900;1,300;1,400;1,500;1,600;1,700;1,800;1,900&amp;display=swap" rel="stylesheet">

<!-- Stylesheets -->
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/font-awesome-all.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/flaticon.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/owl.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/bootstrap.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/jquery.fancybox.min.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/animate.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/jquery-ui.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/nice-select.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/color/theme-color.css') }}" id="jssDefault" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/switcher-style.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/style.css') }}" rel="stylesheet">
<link href="{{ url_for('static', filename='Signin-Signup_Page/assets/css/responsive.css') }}" rel="stylesheet">

</head>


<!-- page wrapper -->
<body>

    <div class="boxed_wrapper">





        <!-- Mobile Menu  -->
        <!-- <div class="mobile-menu">
            <div class="menu-backdrop"></div>
            <div class="close-btn"><i class="fas fa-times"></i></div>
            
            <nav class="menu-box">
                <div class="nav-logo"><a href="dashboard.html"><img src="" alt="" title=""></a></div> -->
                <!-- <div class="menu-outer">Here Menu Will Come Automatically Via Javascript / Same Menu as in Header</div> -->
                <!-- <div class="contact-info">
                    <h4>Contact Info</h4>
                    <ul>
                        <li>Chicago 12, Melborne City, USA</li>
                        <li><a href="tel:+8801682648101">+88 01682648101</a></li>
                        <li><a href="mailto:info@example.com">info@example.com</a></li>
                    </ul>
                </div>
                <div class="social-links">
                    <ul class="clearfix">
                        <li><a href="dashboard.html"><span class="fab fa-twitter"></span></a></li>
                        <li><a href="dashboard.html"><span class="fab fa-facebook-square"></span></a></li>
                        <li><a href="dashboard.html"><span class="fab fa-pinterest-p"></span></a></li>
                        <li><a href="dashboard.html"><span class="fab fa-instagram"></span></a></li>
                        <li><a href="dashboard.html"><span class="fab fa-youtube"></span></a></li>
                    </ul>
                </div>
            </nav> -->
        <!-- </div>End Mobile Menu -->


        <!--Page Title-->
        <section class="page-title-two bg-color-1 centred">
            <div class="pattern-layer">
{#                <div class="pattern-1" style="background-image: url(assets/images/shape/shape-9.png);"></div>#}
{#                <div class="pattern-2" style="background-image: url(assets/images/shape/shape-10.png);"></div>#}
            </div>
            <div class="auto-container">
                <div class="content-box clearfix">
                    <h1>Sign In</h1>
                    <ul class="bread-crumb clearfix">
                        <li><a href="{{ url_for('views.home') }}">Home</a></li>
                        <li>Sign In</li>
                    </ul>
                </div>
            </div>
        </section>
        <!--End Page Title-->


        <!-- ragister-section -->
        <section class="ragister-section centred sec-pad">
            <div class="auto-container">
                <div class="row clearfix">
                    <div class="col-xl-8 col-lg-12 col-md-12 offset-xl-2 big-column">
                        <div class="sec-title">
                            <h5>Sign in</h5>
                            <h2>Sign In With Vuelo Amigo </h2>
                        </div>
                        <div class="tabs-box">
                            <div class="tab-btn-box">
                                <!-- <ul class="tab-btns tab-buttons centred clearfix">
                                    <li class="tab-btn active-btn" data-tab="#tab-1">User</li>
                                    <li class="tab-btn" data-tab="#tab-2">User</li>
                                </ul> -->
                            </div>
                            <div class="tabs-content">
                                <div class="tab active-tab" id="tab-1">
                                    <div class="inner-box">
                                        <h4>Sign in</h4>
                                        <form method="post" class="default-form">
                                            <!-- <div class="form-group">
                                                <label>User name</label>
                                                <input type="text" name="name" required="">
                                            </div> -->
                                            <div class="form-group">
                                                <label>Email address</label>
                                                <input type="email" name="email" required="" class="form-control" id="email">
                                            </div>
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input type="password" name="password" required="" class="form-control" id="password">
                                            </div>
                                            <div class="form-group message-btn">
                                                <button type="submit" class="theme-btn btn-one">Sign in</button>
                                            </div>
                                        </form>
                                        <div class="othre-text">
                                            <p>Have not any account? <a href="{{ url_for('auth.sign_up') }}">Register Now</a></p>
                                        </div>
                                    </div>
                                </div>
                                <!-- <div class="tab" id="tab-2">
                                    <div class="inner-box">
                                        <h4>Sign in</h4>
                                        <form action="http://azim.commonsupport.com/Realshed/signin.html" method="post" class="default-form">
                                            <div class="form-group">
                                                <label>User name</label>
                                                <input type="text" name="name" required="">
                                            </div>
                                            <div class="form-group">
                                                <label>Email address</label>
                                                <input type="email" name="email" required="">
                                            </div>
                                            <div class="form-group">
                                                <label>Password</label>
                                                <input type="password" name="name" required="">
                                            </div>
                                            <div class="form-group message-btn">
                                                <button type="submit" class="theme-btn btn-one">Sign in</button>
                                            </div>
                                        </form>
                                        <div class="othre-text">
                                            <p>Have not any account? <a href="signup.html">Register Now</a></p>
                                        </div>
                                    </div>
                                </div> -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
        <!-- ragister-section end -->






        <!--Scroll to top-->
        <button class="scroll-top scroll-to-target" data-target="html">
            <span class="fal fa-angle-up"></span>
        </button>
    </div>


    <!-- jequery plugins -->
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/jquery.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/popper.min.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/bootstrap.min.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/owl.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/wow.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/validation.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/jquery.fancybox.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/scrollbar.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/isotope.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/jquery.nice-select.min.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/jQuery.style.switcher.min.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/jquery-ui.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/product-filter.js') }}"></script>

    <!-- map script -->
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyA-CE0deH3Jhj6GN4YvdCFZS7DpbXexzGU"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/gmaps.js') }}"></script>
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/map-helper.js') }}"></script>

    <!-- main-js -->
    <script src="{{ url_for('static', filename='Signin-Signup_Page/assets/js/script.js') }}"></script>

</body><!-- End of .page_wrapper -->


</html>